package demo.dboerse.microservices.products.model;
// Generated Aug 13, 2015 3:26:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "Products")
@XmlRootElement
public class Products implements java.io.Serializable {

	private Integer productId;
	private String productName;
	private String productDescription;
	private String unit;
	private BigDecimal price;
	private String currency;

	public Products() {
	}

	public Products(String productName, String unit, BigDecimal price,
			String currency) {
		this.productName = productName;
		this.unit = unit;
		this.price = price;
		this.currency = currency;
	}
	public Products(String productName, String productDescription, String unit,
			BigDecimal price, String currency) {
		this.productName = productName;
		this.productDescription = productDescription;
		this.unit = unit;
		this.price = price;
		this.currency = currency;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = false, length = 25)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_description", length = 50)
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@Column(name = "unit", nullable = false, length = 20)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "currency", nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

}
